version: "3"

services:
  postgres:
    container_name: "dataprism-postgres"
    restart: unless-stopped
    image: "postgres:13"
    ports:
      - "15432:5432"
    volumes:
      - "pgdata:/var/lib/postgresql/data/"
    environment:
      POSTGRES_PASSWORD: postgres

volumes:
  pgdata: {}
